name: vchat
description: A modern voice chat application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.3.8
  animated_text_kit: ^4.2.1
  font_awesome_flutter: ^9.1.0
  sizer: ^2.0.15
  firebase_core: ^1.7.0
  firebase_auth: ^3.1.3
  cloud_firestore: ^3.1.0
  firebase_storage: ^10.0.5
  audioplayers: ^0.20.1
  flutter_easyloading: ^3.0.3
  shared_preferences: ^2.0.8
  flutter_audio_recorder2: ^0.0.2
  path_provider: ^2.0.5
  flutter_ffmpeg: ^0.4.2
  path: ^1.8.0
  loading_indicator: ^3.0.2
  firebase_messaging: ^11.1.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: NanumGothicCoding
      fonts:
        - asset: assets/fonts/NanumGothicCoding-Regular.ttf
        - asset: assets/fonts/NanumGothicCoding-Bold.ttf
          weight: 700
    - family: AmaticSC
      fonts:
        - asset: assets/fonts/AmaticSC-Regular.ttf